const materiaisRecicladosPontosColeta = [

    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":2
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":3
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":4
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":5
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":6
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":7
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":8
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":9
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":10
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":11
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":12
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":13
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":14
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":15
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":16
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":17
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":18
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":19
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":20
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":21
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":22
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":23
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":24
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":25
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":26
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":27
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":28
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":29
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":30
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":31
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":32
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":33
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":34
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":35
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":36
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":37
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":38
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":39
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":40
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":41
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":42
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":43
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":44
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":45
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":46
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":47
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":48
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":49
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":50
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":51
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":52
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":53
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":54
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":55
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":56
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":57
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":58
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":59
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":60
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":61
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":62
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":63
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":64
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":65
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":66
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":67
    },
    { 
        "id_ponto_coleta":1,
        "id_material_reciclado":68
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":2
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":3
    },
    { 
        "id_ponto_coleta":3,
        "id_material_reciclado":4
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":5
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":6
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":7
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":8
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":9
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":10
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":11
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":12
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":13
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":14
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":15
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":16
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":17
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":18
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":19
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":20
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":21
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":22
    },
    { 
        "id_ponto_coleta":3,
        "id_material_reciclado":23
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":24
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":25
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":26
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":27
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":28
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":29
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":30
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":2
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":2
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":2
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":1
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":3
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":3
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":4
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":11
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":22
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":5
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":10
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":15
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":6
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":12
    },
    { 
        "id_ponto_coleta":3,
        "id_material_reciclado":13
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":6
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":50
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":60
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":52
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":53
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":54
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":55
    },
    { 
        "id_ponto_coleta":6,
        "id_material_reciclado":56
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":55
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":58
    },
    { 
        "id_ponto_coleta":3,
        "id_material_reciclado":33
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":60
    },
    { 
        "id_ponto_coleta":10,
        "id_material_reciclado":61
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":62
    },
    { 
        "id_ponto_coleta":4,
        "id_material_reciclado":63
    },
    { 
        "id_ponto_coleta":7,
        "id_material_reciclado":64
    },
    { 
        "id_ponto_coleta":8,
        "id_material_reciclado":65
    },
    { 
        "id_ponto_coleta":9,
        "id_material_reciclado":66
    },
    { 
        "id_ponto_coleta":2,
        "id_material_reciclado":47
    },
    { 
        "id_ponto_coleta":5,
        "id_material_reciclado":68
    }
]

module.exports = materiaisRecicladosPontosColeta;